name: My Checkout
on: push

jobs:
  name-of-job:
    runs-on: ubuntu-latest
    steps:
      - name: List Files
        run: |
          pwd
          ls
      - name: Simple Javascript actions
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: 'James'
      - name: Log Greeting time
        run: echo "${{ steps.greet.outputs.time}}"
