name: my workflow
on: push

jobs:
  name-of-job:
    runs-on: ubuntu-latest
    steps:
      - name: Hello world
        run: |
          write-output "Hello World"
       - name: Hello world
        run: |
          write-output "Hello World"